version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./nginx.conf:/etc/nginx/nginx.conf

  personalsite:
    build: .
    image: personalsite
    container_name: personalsite
    volumes:
      - ./sfjf:/code
      - ./sfjf/media:/code/media
    expose:
      - "80"
    environment:
      - "VIRTUAL_HOST=localhost"
    restart: on-failure
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:80"
